import { toolRegistry } from './registry.js';
import { ReadFileTool } from './fs/readFile.js';
import { WriteFileTool } from './fs/writeFile.js';
import { EditFileTool } from './fs/editFile.js';
import { ListFilesTool } from './fs/listFiles.js';
import { GlobTool } from './fs/glob.js';
import { GrepTool } from './fs/grep.js';
import { BashTool } from './shell/bash.js';
import { RunTestsTool } from './shell/runTests.js';
import { GitDiffTool } from './git/gitDiff.js';
import { GitStatusTool } from './git/gitStatus.js';
import { GitCommitTool } from './git/gitCommit.js';
import { GitRestoreTool } from './git/gitRestore.js';
import { DetectProjectTool } from './project/detectProject.js';
import { InspectProjectTool } from './project/inspectProject.js';
import { SearchSymbolsTool } from './project/searchSymbols.js';
import { WebSearchTool } from './web/search.js';
import { FindSymbolReferencesTool } from './project/findReferences.js';

// Register core tools automatically
toolRegistry.register(new ReadFileTool());
toolRegistry.register(new WriteFileTool());
toolRegistry.register(new EditFileTool());
toolRegistry.register(new ListFilesTool());
toolRegistry.register(new GlobTool());
toolRegistry.register(new GrepTool());
toolRegistry.register(new BashTool());
toolRegistry.register(new RunTestsTool());
toolRegistry.register(new GitDiffTool());
toolRegistry.register(new GitStatusTool());
toolRegistry.register(new GitCommitTool());
toolRegistry.register(new GitRestoreTool());
toolRegistry.register(new DetectProjectTool());
toolRegistry.register(new InspectProjectTool());
toolRegistry.register(new SearchSymbolsTool());
toolRegistry.register(new WebSearchTool());
toolRegistry.register(new FindSymbolReferencesTool());

export * from './types.js';
export * from './registry.js';
export * from './fs/readFile.js';
export * from './fs/writeFile.js';
export * from './fs/editFile.js';
export * from './fs/listFiles.js';
export * from './fs/glob.js';
export * from './fs/grep.js';
export * from './shell/bash.js';
export * from './shell/runTests.js';
export * from './git/gitDiff.js';
export * from './git/gitStatus.js';
export * from './git/gitCommit.js';
export * from './git/gitRestore.js';
export * from './project/detectProject.js';
export * from './project/inspectProject.js';
export * from './project/searchSymbols.js';
export * from './web/search.js';
export * from './project/findReferences.js';
