import { OrbitConfig } from '@orbit-ai/config';
import { ModelProvider } from '@orbit-ai/model-providers';
import { AgentLoop, UserInteraction } from './AgentLoop.js';
import { eventBus } from '../events/EventBus.js';
import fs from 'fs';
import path from 'path';

export class Orchestrator {
  constructor(
    private cwd: string,
    private config: OrbitConfig,
    private provider: ModelProvider,
    private task: string,
    private interaction: UserInteraction
  ) {}

  public async run(): Promise<void> {
    eventBus.emitEvent('agent_start', { taskId: 'multi-agent-session', task: this.task });

    this.interaction.showText(`\n● Starting Multi-Agent Orchestration Flow...`);

    // ==========================================
    // Phase 1: Planning
    // ==========================================
    this.interaction.showText(`\n[Phase 1: Planning] Initializing Planner Agent...`);
    const plannerLoop = new AgentLoop(
      this.cwd,
      this.config,
      this.provider,
      `Create a detailed implementation plan for: ${this.task}`,
      this.interaction,
      {
        modelOverride: this.config.models.planner,
        systemPromptOverride: `You are the Orbit Planner Agent.
Analyze the codebase structure, relevant files, and design choices to build a detailed, step-by-step implementation plan.
Do NOT modify any files yourself. Focus entirely on formulating the best approach.
Your final response MUST present the detailed plan clearly.`,
        allowedTools: [
          'read_file',
          'list_files',
          'glob',
          'grep',
          'git_status',
          'git_diff',
          'detect_project',
          'inspect_project',
        ],
      }
    );
    await plannerLoop.run();

    // Extract the plan from the final message in history
    const plannerHistory = plannerLoop.getHistory();
    const lastPlannerMsg = plannerHistory[plannerHistory.length - 1];
    const planText = lastPlannerMsg?.content
      .map((c) => (c.type === 'text' ? c.text : ''))
      .join('\n') || 'No plan generated.';

    this.interaction.showText(`\n● Plan generated by Planner Agent. Saving to orbit_plan.md...`);
    try {
      fs.writeFileSync(path.resolve(this.cwd, 'orbit_plan.md'), planText, 'utf8');
      this.interaction.showText(`  ✔ Plan successfully written to orbit_plan.md`);
    } catch (err: any) {
      this.interaction.showText(`  ✖ Failed to write plan to orbit_plan.md: ${err.message}`);
    }

    // ==========================================
    // Phase 2 & 3: Coding and Review loop
    // ==========================================
    let reviewPassed = false;
    let feedback = '';
    let attempt = 0;
    const maxAttempts = 3;

    while (!reviewPassed && attempt < maxAttempts) {
      attempt++;
      this.interaction.showText(
        `\n[Phase 2: Coding (Attempt ${attempt}/${maxAttempts})] Initializing Coder Agent...`
      );

      const coderPrompt =
        attempt === 1
          ? `Implement the changes outlined in the plan.\nPlan:\n${planText}`
          : `Fix the issues reported by the Reviewer Agent.\nFeedback:\n${feedback}\n\nOriginal Plan:\n${planText}`;

      const coderLoop = new AgentLoop(
        this.cwd,
        this.config,
        this.provider,
        coderPrompt,
        this.interaction,
        {
          modelOverride: this.config.models.coder,
          systemPromptOverride: `You are the Orbit Coder Agent.
Your job is to read files and make precise edits to code files according to the plan.
You do NOT have bash command execution or testing capabilities. Focus entirely on modifying the codebase correctly.`,
          allowedTools: [
            'read_file',
            'write_file',
            'edit_file',
            'list_files',
            'glob',
            'grep',
            'git_status',
            'git_diff',
          ],
        }
      );
      await coderLoop.run();

      this.interaction.showText(
        `\n[Phase 3: Review (Attempt ${attempt}/${maxAttempts})] Initializing Reviewer Agent...`
      );

      const reviewerPrompt = `Verify if the changes made by the Coder Agent are correct. Run tests and review the git diff to identify any issues.`;

      const reviewerLoop = new AgentLoop(
        this.cwd,
        this.config,
        this.provider,
        reviewerPrompt,
        this.interaction,
        {
          modelOverride: this.config.models.reviewer,
          systemPromptOverride: `You are the Orbit Reviewer Agent.
Your job is to check the codebase diff and run project tests to ensure correctness.
You do NOT have file editing or write capabilities.
If all tests pass and the changes look correct and conform to guidelines, respond with "APPROVED" as the main keyword.
If there are failures or issues (syntax errors, lint warnings, test failures), list them clearly to help the Coder Agent fix them.`,
          allowedTools: [
            'read_file',
            'list_files',
            'glob',
            'grep',
            'git_status',
            'git_diff',
            'run_tests',
            'bash',
          ],
        }
      );
      await reviewerLoop.run();

      const reviewerHistory = reviewerLoop.getHistory();
      const lastReviewMsg = reviewerHistory[reviewerHistory.length - 1];
      const reviewerResponse =
        lastReviewMsg?.content
          .map((c) => (c.type === 'text' ? c.text : ''))
          .join('\n') || '';

      if (reviewerResponse.toUpperCase().includes('APPROVED')) {
        reviewPassed = true;
        this.interaction.showText(`\n✔ Review Passed! Multi-agent task execution completed successfully.`);
      } else {
        feedback = reviewerResponse;
        this.interaction.showText(
          `\n✖ Review Failed. Feedback and test results passed back to Coder Agent.`
        );
      }
    }

    if (!reviewPassed) {
      this.interaction.showText(
        `\n✖ Orchestration finished: Failed to pass review after ${maxAttempts} attempts.`
      );
    }
  }
}
